### ISSUE TITLE
ImportError: No module named 'pytest'

### ISSUE THREAD

**Issue by SamsadSajid** [matplotlib/mpl-probscale#60]
* Python version: 3.5.2
* numpy version: 1.15.0
* matplotlib version: 2.2.2
* mpl-probscale version: Error
* Operating System: Ubuntu 16.04

### Description

Whenever I am trying to import `import probscale` I am getting the following error:

> File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/probscale/__init__.py", line 5, in <module>
>     from .tests import test
>   File "/usr/local/lib/python3.5/dist-packages/probscale/tests/__init__.py", line 3, in <module>
>     import pytest
> ImportError: No module named 'pytest'

### What I Did
I searched for if there's any dependency on **pytest** but couldn't find it either in **Github** nor in the documentation.

### How did I install?
I installed with pip3
`sudo -H pip3 install probscale`

**Comment by phobson** [comment]
@SamsadSajid this is fixed in master, but not release. Installing purest (via pip, for example) will fix this.

**Comment by SamsadSajid** [comment]
I installed with `pip3` as I mentioned above but I got the error!! I installed `pytest` manually then

**Comment by phobson** [comment]
Oh sorry, autocorrect mangled my message.

Yes this is a bug in the released version of mpl-probscale.

If you do `pip3 install pytest`, it will fix it.

**Comment by SamsadSajid** [comment]
Shouldn't it be written on the `README.md` section?

**Comment by phobson** [comment]
Yes. Could you submit a PR?

**Comment by SamsadSajid** [comment]
I can't submit a Pull Request. The Create new request button is
unclickable!!!!
