### ISSUE TITLE
Invalid value encountered in sign when using probscale after sns.boxplot

### ISSUE THREAD

**Issue by Tau-Neutrino** [matplotlib/mpl-probscale#65]
* Python version:      3.7.3
* numpy version:    1.16.4
* matplotlib version:  3.1.1
* mpl-probscale version: 0.2.3
* Operating System: Win 10 

### Description

Hi,

when I do a probscale plot after a sns.boxplot I get the following warnings:
```
probscale.py:44: RuntimeWarning: invalid value encountered in sign
  return numpy.sign(z) * numpy.sqrt(numpy.sqrt(_b**2 - _c) - _b)

probscale.py:32: RuntimeWarning: invalid value encountered in sign
  return numpy.sign(x) * numpy.sqrt(1.0 - numpy.exp(guts))
```

Now the strange thing: If i do only the sns.boxplot I get no warning. The same is true if i only do the probplot. Seems like there is some kind of interaction?

### What I Did

Import modules and data:
```
import pandas as pd

import seaborn as sns

import probscale

import matplotlib.pyplot as plt

df = pd.read_excel('data.xlsx')

```

sns boxplot:
```
plt.figure('box')

sns.boxplot(x=df['Wafer'], y = df['VGSTH_NOM'], showfliers=False)
```
​
probplot:
```
plt.figure('cf')
for wafer in pd.unique(df['Wafer']):
    probscale.probplot(df.loc[df['Wafer']== wafer,'VGSTH_NOM'], plottype='prob', probax='y')
```
​
show plots:
```
plt.show()
```

Output:
```
probscale.py:44: RuntimeWarning: invalid value encountered in sign
  return numpy.sign(z) * numpy.sqrt(numpy.sqrt(_b**2 - _c) - _b)
probscale.py:32: RuntimeWarning: invalid value encountered in sign
  return numpy.sign(x) * numpy.sqrt(1.0 - numpy.exp(guts))
```

Data is attached.

Might be something simple - but I did not manage to find the reason for the warning. 
Cheers,
Gerald

[debug.zip](https://github.com/matplotlib/mpl-probscale/files/3485558/debug.zip)

**Comment by phobson** [comment]
Do you have negative data in your dataset? Can you make a reproducible example? I don't have data.xlsx so it's hard to know what's going on.

**Comment by Tau-Neutrino** [comment]
Hi, 
the source data is attached to the first post - see the "debug.zip" file.

**Comment by phobson** [comment]
As a general policy, I don't extract zip files from strangers. Could you hard-code the a small sample of the data that reproduces the issue into your example?

**Comment by StefRe** [comment]
The warning occurs as `numpy.sign` is being called for an array with a `nan` value. This seems to be a Windows specific problem: `numpy.sign([numpy.nan])` raises a warning on Windows (Python 3.7.3) but not on Linux (Python 3.6.8) for the same numpy version 1.17.3.

During the autoscaling of the y-axis, `limit_range_for_scale` is called with `(0, 1, inf)` and returns `inf, 1`. The inverse transform then yields `nan, -2.32...` for these values. 

Probably this warning should be suppressed in  `_approx_erf` and  `_approx_inv_erf`. See also [this numpy issue](https://github.com/numpy/numpy/issues/8945#issuecomment-431594610).

**Comment by phobson** [comment]
Thanks for sleuthing the source of this @StefRe. I probably won't be able to work on this for a while. I'd happily review and merge a PR that suppresses the warning.
