### ISSUE TITLE
documentation website no longer functional

### ISSUE THREAD

**Issue by musm** [matplotlib/mpl-probscale#86]
* Python version:
* numpy version:
* matplotlib version:
* mpl-probscale version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by phobson** [comment]
Hey -- thanks for letting me know about this. MPL's docs got reorganized and I haven't caught up to that yet. 

In the meantime, the notebooks can serve as a guide: https://github.com/matplotlib/mpl-probscale/tree/master/docs/tutorial

**Comment by QuLogic** [comment]
These have been restored: https://github.com/matplotlib/matplotlib.github.com/pull/80
